# Generated by Django 4.2.1 on 2023-05-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collegeapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courses",
            old_name="name",
            new_name="cname",
        ),
    ]
