# Generated by Django 4.2.1 on 2023-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collegeapp", "0002_rename_name_courses_cname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courses",
            name="id",
        ),
        migrations.RemoveField(
            model_name="department",
            name="id",
        ),
        migrations.AddField(
            model_name="courses",
            name="cid",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="courses",
            name="did",
            field=models.IntegerField(default="100"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="did",
            field=models.IntegerField(
                default="exit", primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
