# Generated by Django 4.2.1 on 2023-05-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collegeapp",
            "0003_remove_courses_id_remove_department_id_courses_cid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courses",
            name="cid",
        ),
        migrations.RemoveField(
            model_name="courses",
            name="did",
        ),
        migrations.RemoveField(
            model_name="department",
            name="did",
        ),
        migrations.AddField(
            model_name="courses",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default="exit100",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default="exit",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
